### ISSUE TITLE
IExecutor current returns bare pointer to ITimer*, should it?

### ISSUE THREAD

**Issue by jadamcrain** [automatak/openpal#2]
It would probably be safer to return std::shared_ptr<ITimer>.

Canceling a timer would then be idempotent, and the timer would remain in memory until all instances are released.

**Comment by emgre** [comment]
A timer lives for the duration of itself. A weak_ptr would be my first choice. But it makes sense to make it live while we still hold one, but it doesn't really make sense to cancel an already expired one... So why hold it in the first place?

**Comment by jadamcrain** [comment]
weak_ptr<ITimer> is a good suggestion. This would allow the memory to be freed immediately after the timer fires or is canceled, but would turn a seg-fault into std::bad_weak_ptr if someone misuses the timer.

You would never intentionally hold onto a timer after it fires. I'm just looking to make the interface safer in case someone does do it.

**Comment by emgre** [comment]
I like that, +1

**Comment by jadamcrain** [comment]
https://github.com/automatak/openpal/blob/master/cpp/libs/include/openpal/executor/Timer.h
